apiVersion: v1
kind: Service
metadata:
  name: elasticache-poc-service
  labels:
    app: elasticache-poc
spec:
  selector:
    app: elasticache-poc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080